openapi: 3.0.3
info:
  title: MyRoad
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8009'
paths:
  /api/v1/login:
    post:
      summary: Login
      operationId: login
      description: 'Authenticates a user and returns an API token'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Invalid login details'
                properties:
                  message:
                    type: string
                    example: 'Invalid login details'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The email of the user.'
                  example: admin@example.com
                password:
                  type: string
                  description: 'The password of the user.'
                  example: "password\n\nuse editor@example.com and password for different permissions"
              required:
                - email
                - password
      security: []
  /api/v1/tours:
    post:
      summary: 'Store a new Tour'
      operationId: storeANewTour
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Tour Endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                travelId:
                  type: string
                  description: 'The id of the travel.'
                  example: cbf304ae-a335-43fa-9e56-811612dcb601
                startingDate:
                  type: string
                  description: 'The starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2024-01-01'
                endingDate:
                  type: string
                  description: 'The ending date of the tour. Must be a valid date in the format <code>Y-m-d</code>. Must be a date after <code>startingDate</code>.'
                  example: '2024-01-08'
                price:
                  type: integer
                  description: 'The price of the tour. Must be at least 1.'
                  example: 1000
              required:
                - travelId
                - startingDate
                - endingDate
                - price
  '/api/v1/travel/{travel_slug}/tours':
    get:
      summary: 'Get tours by travel slug'
      operationId: getToursByTravelSlug
      description: ''
      parameters:
        -
          in: query
          name: priceFrom
          description: 'The minimum price of the tour.'
          example: 100.0
          required: false
          schema:
            type: number
            description: 'The minimum price of the tour.'
            example: 100.0
        -
          in: query
          name: priceTo
          description: 'The maximum price of the tour.'
          example: 10000.0
          required: false
          schema:
            type: number
            description: 'The maximum price of the tour.'
            example: 10000.0
        -
          in: query
          name: dateFrom
          description: 'The minimum starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
          example: '2024-01-01'
          required: false
          schema:
            type: string
            description: 'The minimum starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
            example: '2024-01-01'
        -
          in: query
          name: dateTo
          description: 'The maximum starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
          example: '2024-12-31'
          required: false
          schema:
            type: string
            description: 'The maximum starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
            example: '2024-12-31'
        -
          in: query
          name: sortBy
          description: 'The field to sort by.'
          example: price
          required: false
          schema:
            type: string
            description: 'The field to sort by.'
            example: price
            enum:
              - price
        -
          in: query
          name: sortOrder
          description: 'The order to sort by.'
          example: asc
          required: false
          schema:
            type: string
            description: 'The order to sort by.'
            example: asc
            enum:
              - asc
              - desc
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 9b1ef570-7910-4cff-b26d-677da3fdd9f9
                      travelId: cbf304ae-a335-43fa-9e56-811612dcb601
                      name: ITUNI20240101
                      startingDate: '2024-01-01'
                      endingDate: '2024-01-08'
                      price: 1000
                    -
                      id: 90155d92-01e5-4c4b-a5a8-e24011fa8418
                      travelId: cbf304ae-a335-43fa-9e56-811612dcb601
                      name: ITUNI20240121
                      startingDate: '2024-01-21'
                      endingDate: '2024-01-28'
                      price: 1799
                  links:
                    first: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=1'
                    last: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=2'
                    prev: null
                    next: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=2'
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 2
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=1'
                        label: '1'
                        active: true
                      -
                        url: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=2'
                        label: '2'
                        active: false
                      -
                        url: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=2'
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours'
                    per_page: 2
                    to: 2
                    total: 4
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 9b1ef570-7910-4cff-b26d-677da3fdd9f9
                        travelId: cbf304ae-a335-43fa-9e56-811612dcb601
                        name: ITUNI20240101
                        startingDate: '2024-01-01'
                        endingDate: '2024-01-08'
                        price: 1000
                      -
                        id: 90155d92-01e5-4c4b-a5a8-e24011fa8418
                        travelId: cbf304ae-a335-43fa-9e56-811612dcb601
                        name: ITUNI20240121
                        startingDate: '2024-01-21'
                        endingDate: '2024-01-28'
                        price: 1799
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 9b1ef570-7910-4cff-b26d-677da3fdd9f9
                        travelId:
                          type: string
                          example: cbf304ae-a335-43fa-9e56-811612dcb601
                        name:
                          type: string
                          example: ITUNI20240101
                        startingDate:
                          type: string
                          example: '2024-01-01'
                        endingDate:
                          type: string
                          example: '2024-01-08'
                        price:
                          type: integer
                          example: 1000
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=1'
                      last:
                        type: string
                        example: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=2'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=2'
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 2
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=1'
                            label: '1'
                            active: true
                          -
                            url: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=2'
                            label: '2'
                            active: false
                          -
                            url: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?priceFrom=100&priceTo=10000&dateFrom=2024-01-01&dateTo=2024-12-31&sortBy=price&sortOrder=asc&page=2'
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours'
                      per_page:
                        type: integer
                        example: 2
                      to:
                        type: integer
                        example: 2
                      total:
                        type: integer
                        example: 4
      tags:
        - 'Tour Endpoints'
    parameters:
      -
        in: path
        name: travel_slug
        description: 'The slug of the travel.'
        example: united-arab-emirates-from-dubai-to-abu-dhabi
        required: true
        schema:
          type: string
  /api/v1/travels:
    post:
      summary: 'Store a new Travel'
      operationId: storeANewTravel
      description: 'Create a new travel'
      parameters: []
      responses:
        201:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n\"data\": {\n  \"id\": \"9b1bff16-e089-41de-8d4f-9e87f9014139\",\n  \"name\": \"Jordan 360\",\n  \"slug\": \"jordan-360\",\n  \"description\": \"Jordan 360°: the perfect tour to....\",\n  \"numberOfDays\": 8,\n  \"numberOfNight\": 7,\n  \"moods\": {\n      \"nature\": 80,\n      \"relax\": 20,\n      \"history\": 90,\n      \"culture\": 30,\n      \"party\": 10\n  }\n}"
      tags:
        - 'Travel Endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the travel. Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: 'Jordan 361'
                description:
                  type: string
                  description: 'The description of the travel. Must be at least 2 characters. Must not be greater than 2000 characters.'
                  example: 'Jordan 361°: the perfect tour to....'
                numberOfDays:
                  type: integer
                  description: 'The number of days of the travel. Must be at least 1. Must not be greater than 1000.'
                  example: 5
                visibility:
                  type: string
                  description: 'The visibility of the travel (public or private).'
                  example: public
                  enum:
                    - public
                    - private
                moods:
                  type: string
                  description: 'The moods of the travel.'
                  example: '{"nature": 80,"relax": 20,"history": 90,"culture": 30,"party": 10}'
              required:
                - name
                - description
                - numberOfDays
                - visibility
                - moods
  '/api/v1/travels/{id}':
    put:
      summary: 'Update a Travel'
      operationId: updateATravel
      description: 'Update a travel'
      parameters: []
      responses: {  }
      tags:
        - 'Travel Endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the travel. Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: 'Jordan 361'
                description:
                  type: string
                  description: 'The description of the travel. Must be at least 2 characters. Must not be greater than 2000 characters.'
                  example: 'Jordan 361°: the perfect tour to....'
                numberOfDays:
                  type: integer
                  description: 'The number of days of the travel. Must be at least 1. Must not be greater than 1000.'
                  example: 5
                visibility:
                  type: string
                  description: 'The visibility of the travel (public or private).'
                  example: public
                  enum:
                    - public
                    - private
                moods:
                  type: string
                  description: 'The moods of the travel.'
                  example: '{"nature": 80,"relax": 20,"history": 90,"culture": 30,"party": 10}'
              required:
                - name
                - description
                - numberOfDays
                - visibility
                - moods
    parameters:
      -
        in: path
        name: id
        description: 'Optional parameter. uuid required The ID of the travel.<br>'
        required: true
        schema:
          type: string
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: d408be33-aa6a-4c73-a2c8-58a70ab2ba4d
tags:
  -
    name: Authentication
    description: "\nAPIs for user authentication"
  -
    name: 'Tour Endpoints'
    description: ''
  -
    name: 'Travel Endpoints'
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by login endpoint.'
security:
  -
    default: []
